CREATE DATABASE college;
USE college;
CREATE TABLE student (
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL
);
INSERT INTO student VALUES(1,"ABHA",23);
INSERT INTO student VALUES(2,"BHUMI",24);
INSERT INTO student VALUES(3,"CHARU",22);
SELECT * FROM student;


